### ISSUE TITLE
coloring is not cleared properly and affects other schemes

### ISSUE THREAD

**Issue by jan-warchol** [lifepillar/vim-colortemplate#26] opened 2020-03-27 22:23 UTC
Let's say I have this template:

```
# vim: ft=colortemplate
Full name:  example for bug report
Short name: test
Author:     JW <jan.warchol@gmail.com>

Background: dark

# Color palette
Color: bg_0          #181818        ~        none
Color: fg_0          #b9b9b9        ~        none
Color: green         #70b433        ~        DarkGreen

# Highlight group definitions
Variant:    gui 256 8

Normal        none  none
ShDerefSimple green none
ShDerefVar    green none
```
When I start Vim with default colorscheme, a piece of shell script will look like this (note magenta var `HISTFILE`):
![image](https://user-images.githubusercontent.com/1368508/77805116-7a1c7980-7081-11ea-97e9-1c567428f0f6.png)

Then I switch to the scheme generated with colortemplate (`:colorscheme test`), and vars become green:
![image](https://user-images.githubusercontent.com/1368508/77805190-9ddfbf80-7081-11ea-8060-5bf726329bd2.png)

So far so good. But when I try to go back (`:colorscheme default`), vars are... not colored at all:
![image](https://user-images.githubusercontent.com/1368508/77805286-ce275e00-7081-11ea-8421-29ee2ccc16a3.png)

So, it seems there are some leftovers that affect other schemes :/

It happens in vim and gvim, version 7.4 and 8.0.

**Comment by arzg** [comment] 2020-03-28 01:40
This kind of behaviour affects all Vim colour schemes; it is actually a very long running issue and I believe was [first noticed with the Solarized colour scheme](https://github.com/altercation/solarized/issues/102).

**Comment by lifepillar** [comment] 2020-04-01 13:39
Duplicate of https://github.com/lifepillar/vim-colortemplate/issues/3.

**Closed by lifepillar** 2020-04-01 13:39 UTC

**Comment by lifepillar** [comment] 2020-04-01 13:41
The issue is still open in [Vim's official repo](https://github.com/vim/vim/issues/4405).

**Comment by jan-warchol** [comment] 2020-04-01 13:44
Oh, sorry! I forgot to reply. I see. It's very sad of vim, but anyway thanks for helping me out @arzg and @lifepillar! I found a sort-of-workaround by playing with default groups in more detail.
