### ISSUE TITLE
Great idea.

### ISSUE THREAD

**Issue by jordwalke** [lifepillar/vim-colortemplate#2] opened 2017-10-28 21:11 UTC
This is a great idea. Here's a couple of suggestions/ideas.

- You might take a look at @xolox's comment [here](https://github.com/altercation/solarized/issues/102#issuecomment-18109651) about some known issues with colorscheme switching. If creating a template for other plugins to be based on, there might be some problems with colorscheming you can fix at the template level.
- Should this template include vim-airline support?

**Comment by lifepillar** [comment] 2017-10-30 19:42
Thanks for your feedback!

Re your first point, I see that the issue can still be reproduced with Solarized8. If I understand correctly, it depends on Solarized defining syntax highlight groups for specific filetypes (e.g., Vim) with, say, `hi vimCommand…` rather than `hi link vimCommand…`. I vaguely remember something similar discussed in Vim mailing list, but I don't remember the details. If following some rules can prevent messing with syntax highlighting, I will certainly enforce them (and update Solarized8 accordingly—curious that no one has reported the issue yet).

Re vim-airline support, what would that entail? Isn't it just a matter of defining some custom highlight groups? For things like other plugins's support, I'd be more keen to add customization points for those plugins to hook into rather than hard code something in colortemplate.

**Comment by lifepillar** [comment] 2017-10-30 19:59
The thread I had in mind is *"syntax reset" in colorschemes* from vim-dev, btw.

**Comment by jordwalke** [comment] 2017-10-30 20:10
> "Re vim-airline support, what would that entail? Isn't it just a matter of defining some custom highlight groups? For things like other plugins's support, I'd be more keen to add customization points for those plugins to hook into rather than hard code something in colortemplate."

It involves creating a separate `.vim` file in the `autoload` directory. `vim-airline` is so popular that you might consider just including it out of the box as part of the template. It wouldn't hurt anyone if airline wasn't installed.

**Comment by lifepillar** [comment] 2017-11-01 09:03
Since these are two distinct issues, I have opened https://github.com/lifepillar/vim-colortemplate/issues/3 and https://github.com/lifepillar/vim-colortemplate/issues/4. So I am closing this. Feel free to continue the discussion there.

**Closed by lifepillar** 2017-11-01 09:03 UTC
